### ISSUE TITLE
Pictures not uploading via Apps

### ISSUE THREAD

**Issue by OneTwoBarbecue** [mattermost/mattermost-plugin-antivirus#14]
Dear mattermost-antivirus-plugin-team, 

I'm experiencing issues when uploading photos from the mobile apps when the antivirus-plugin is active. The jpg-upload fails randomly after finishing a high amount of percentage - e.g. 99% and then the round retry-arrow is shown.

I'm running a Mattermost-Instance on a 64bit Intel QNAP-NAS as VM with 3GB memory assigned on Ubuntu 18.04. It works behind a NGINX-reverse-proxy where the recommended configuration is used. Performance is very well.

Interestingly it's only the mobile apps that cause the issue, web-access and uploads work as expected when used via browser - even when using a mobile device.

Unfortunately nether are errors shown in the mattermost server logs nor in the NGIX-logs.

I tried using the clamav-docker and tried a local clamav-installations as well. Both didn't work reliable and caused the issues.

Mattermost version is 5.17.1, database-scheme is 5.17.0, apps are up-to-date and I'm using the latest version of the antivirus-plugin.

I thought it might be interesting for you to be aware of the issue.

**Comment by crspeller** [comment]
@OneTwoBarbecue Thanks for the report. Are you sure the problem is coming from the Antivirus plugin? Does the problem persist if you remove the plugin? If the antivirus plugin is rejecting the file, there should be a log entry.

**Comment by OneTwoBarbecue** [comment]
@crspeller Thanks for the reply. As I said, I couldn't find any errors in any logfile. I checked the syslog, the mattermost logs and the logs from clamav. I reproduced the error once again to verify - again no error shown. I was wondering, if there is some kind of timeout used by the plugin that doesn't show any error messages. Or that there is some kind of timeout used by the apps which wouldn't show any error messages as well. Perhaps I should mention that I use a 50mbit download/10mbit upload connection. The error only occurs when connecting via the mobile app and usually but somehow randomly. Sometimes reloading the upload various times works. I tried different jpg-filesizes and was unfortunately unable to find out any relations to the jpg-filesize. Hope that helps.

**Comment by crspeller** [comment]
@OneTwoBarbecue Does the problem persist if you remove the plugin?

**Comment by OneTwoBarbecue** [comment]
@crspeller  The problem does not occur when the plugin is switched of in the plugin-administration shown in the system console of mattermost. I run Mattermost with file list plugin and zoom plugin activated. After turning the plugin of I restarted the mattermost server service from within a terminal to ensure that the new settings will take effect (what they probably do without restarting the service). With antivirus-plugin turned off everything works as expected.

**Comment by crspeller** [comment]
@OneTwoBarbecue This does seem like an issue then. I will see if I can reproduce myself.

**Comment by Rock980** [comment]
Hi team,

Our plugin version is Antivirus (antivirus - 0.1.2)

When plugin is on, we are ok to upload files, but copy-paste picture.
it shows, "Unable to upload file Image Pasted at 2020-3-10 18-55.png. Rejected by plugin: File Scanning Server unreachable, contact your Mattermost administrator for assistance."

Once plugin is off, upload file and paste picture are both fine.

**Comment by OneTwoBarbecue** [comment]
Hi team, 

during the past weeks I had intense contact to the mattermost-app-team and finally we did find out that the problem and especially the differences in using the browser-application compared to using the app is due to a timout which is implemented [here](https://github.com/mattermost/mattermost-mobile/blame/1a605891fee325f7913238657e91565f52da863d/app/components/post_draft/uploads/upload_item/upload_item.js#L154).
The team did provide a beta version to me with increased timeout-values and now the antivirus-plugin works like a charm.
So the problem is not related to the antivirus-plugin and I do close the issue right here.

Thank you very much to everybody for digging into this! Keep on developping this great peace of software - and what's most important at the moment - stay healthy !
