### ISSUE TITLE
Add codecov.io webhook to the github repository

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-antivirus#19]
This tasks needs somebody that has access to edit settings for this repo.

Once resolved, we can merge https://github.com/mattermost/mattermost-plugin-antivirus/pull/20

**Comment by hanzei** [comment]
@jfrerich Could you elaborate a bit? What webhook is needed? Other repos use a specific circleci job: https://github.com/mattermost/mattermost-plugin-github/blob/b1e3667dc7e6823e22df1ba7eeb180fbcdc36b61/.circleci/config.yml#L14-L17

**Comment by jfrerich** [comment]
@hanzei, the circleci job does create the report, but the github webhook that tells circleci to run on each commit has to be created.  To do this, a user with GH admin privileges needs to goto https://codecov.io/gh/mattermost/mattermost-plugin-antivirus/settings and click this button
![image](https://user-images.githubusercontent.com/7575921/83574833-df627000-a4f3-11ea-99b8-31046e5fa358.png)

**Comment by jfrerich** [comment]
Do you have admin privileges for this repo and could you click the button? :)

**Comment by hanzei** [comment]
Good point @jfrerich I didn't know that this was needed. I don't have the privileges to do that.

@levb Could you help? (Maybe even do this for all plugin repos?)

**Comment by jfrerich** [comment]
Users not having admin privileges to plugin repos has been a pain point for intake and modifications. I would like to propose a Github "group" that includes the integration team members and is added to each repo.

**Comment by hanzei** [comment]
Should be working now
![Screenshot from 2021-05-27 14-15-53](https://user-images.githubusercontent.com/16541325/119824328-13e5ed80-bef6-11eb-8c69-7edfa0d51425.png)
