### ISSUE TITLE
Feature Request: support using unix socket to connect to the ClamAV daemon

### ISSUE THREAD

**Issue by PeterDaveHello** [mattermost/mattermost-plugin-antivirus#25]
Can we have the unix socket support to connect to the ClamAV daemon?

On Debian/Ubuntu/Alpine Linux, ClamAV daemon's unix socket is default enabled, but TCP's is not, it'll be great if this plugin would like to support the ability to use unix socket.

Thanks!

**Comment by hanzei** [comment]
Good suggestion @PeterDaveHello :+1: Are you interested in implementing it?

**Comment by PeterDaveHello** [comment]
Well, I haven't learned to write golang yet, maybe one day ;) But I can help test the feature if you need!

**Comment by hanzei** [comment]
Thanks for the offer :+1: Will reach out once someone picks this up.

**Comment by maisnamrajusingh** [comment]
@hanzei  @PeterDaveHello would it make sense to provide an option in the config settings for the user to select either TCP or UNIX as an option ?

**Comment by PeterDaveHello** [comment]
@maisnamrajusingh sure thing!
