### ISSUE TITLE
Pasted images fail to upload due to antivirus.

### ISSUE THREAD

**Issue by tjdownes** [mattermost/mattermost-plugin-antivirus#26]
![image](https://user-images.githubusercontent.com/273720/98617607-3c88fb80-22b4-11eb-851f-04c6f4fb9536.png)

I am using the DigitalOcean droplet and running version 5.16.3 of Mattermost with mpa 0.1.1

**Comment by hanzei** [comment]
Well, that is kind of the expected behaviour. If the ClamAV server can be reached, the plugin falls back to the most conservative behaviour and rejects all attachments.

**Comment by tjdownes** [comment]
> Well, that is kind of the expected behaviour. If the ClamAV server can be reached, the plugin falls back to the most conservative behaviour and rejects all attachments.

I'm not sure what you mean here. The server is available and works for ALL OTHER attachments. Only pasted attachments fail, which breaks the ability to paste images. In this case, if the AV is unable to scan pasted images as part of it's functionality, then it probably should not even try to scan pasted images. If it should be able to scan pasted images, then this is a bug that should be fixed.

**Comment by hanzei** [comment]
Just to double check: The plugin rejects an image if you past it, but accepts the same image if you upload it directly?

**Comment by tjdownes** [comment]
Yes, that is correct

**Comment by maisnamrajusingh** [comment]
@tjdownes could you post the server logs if possible and possibly the image

**Comment by maisnamrajusingh** [comment]
@tjdownes did you manage to resolve this ?

**Comment by tjdownes** [comment]
I did not. Sorry for the late reply, but I have to reconfigure the server again. I'll do so tonight and try to post logs and an image for you

**Comment by tjdownes** [comment]
@maisnamrajusingh I installed clamav and configured the plugin and now pasted images work fine to upload. Possibly something with the clamav version I was using back in May? Regardless, it seems this can now be closed. Thanks for following up.
