### ISSUE TITLE
Throw a server connect error more clearly

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-plugin-antivirus#7]
If MM can't connect to the clamav server, the returned error is not very clear.  You'll notice that it's not working because you can't post any attachments at all and the error says "Error while scanning for viruses"

![2019-07-26_11-52-33](https://user-images.githubusercontent.com/915956/62154381-6be04880-b2bb-11e9-8fbb-d5e6d70677bb.png)

**Comment by Lumexralph** [comment]
@hanzei I would love to help with this

**Comment by dialytica** [comment]
I want to take this issue. Gonna have the pull request soon.

**Comment by hanzei** [comment]
Awesome! Thanks for working on this @Lumexralph :+1:

**Comment by Lumexralph** [comment]
@aaronrothschild How can I reproduce the issue locally? Also, what kind of error message do you think or suggest should be displayed?
@hanzei

**Comment by hanzei** [comment]
@Lumexralph You can just configure the Host and Port to something invalid in Step 4 of the installation process (https://github.com/mattermost/mattermost-plugin-antivirus#installation)

**Comment by Lumexralph** [comment]
@aaronrothschild what kind of error message do you think or suggest should be displayed?

**Comment by aaronrothschild** [comment]
> @aaronrothschild what kind of error message do you think or suggest should be displayed?

@Lumexralph Sorry for the missed reply.  I'd suggest something like "File Scanning Server unreachable, contact your Mattermost administrator for assistance"

**Comment by levb** [comment]
@Lumexralph Are you interested in finishing this ticket, or should we put it back up for grabs?

**Comment by anidok** [comment]
@levb I would like to take up this one.

**Comment by hanzei** [comment]
Thanks @anidok :+1:
